### ISSUE TITLE
Unsupported operation

### ISSUE THREAD

**Issue by trihoang1810** [xclud/flutter_map#21]
Guys, when I try to build the Map(), this cause the problem:
```console
he following UnsupportedError was thrown building LayoutBuilder:
Unsupported operation: Infinity or NaN toInt

The relevant error-causing widget was
Map
lib\main.dart:140
When the exception was thrown, this was the stack
#0      double.toInt (dart:core-patch/double.dart:219:36)
#1      double.ceil (dart:core-patch/double.dart:184:32)
#2      _MapState._build
package:map/src/map.dart:68
#3      _LayoutBuilderElement._layout.<anonymous closure>
package:flutter/…/widgets/layout_builder.dart:121
#4      BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2647
...
```
I didn't see the Map's properties that can limit the size, please help

```

**Comment by trihoang1810** [comment]
The only thing I change of this pub example that I add a container 400x400 and Divider to the UI

**Comment by trihoang1810** [comment]
I can see the problem here:
In the map.dart, the ``size`` take the max width as well as max height of the device:
```
Widget _build(BuildContext context, BoxConstraints constraints) {
    final controller = widget.controller;
    final tileSize = controller.tileSize;
    final size = constraints.biggest;
    final projection = controller.projection;
```
But I actually don't know how to change this value, I think when I change this value, it can lay impact on the pub

**Comment by xclud** [comment]
Can you paste a whole dart file?
